#define LAUNCHPAD_VERSION_STRING "0.0.1"

#define LAUNCHPAD_VERSION_MAJOR 0
#define LAUNCHPAD_VERSION_MINOR 0
#define LAUNCHPAD_VERSION_RELEASE 1

#define LAUNCHPAD_MAKE_VERSION(a,b,c) (((a) << 16) | ((b) << 8) | (c))

#define LAUNCHPAD_VERSION LAUNCHPAD_MAKE_VERSION(LAUNCHPAD_VERSION_MAJOR, LAUNCHPAD_VERSION_MINOR, LAUNCHPAD_VERSION_RELEASE)

namespace Launchpad
{

}
